In [8]:
import cv2
import numpy as np
import matplotlib.pyplot as plt

In [9]:
img=cv2.imread(r"c:\Bir.jpg")

In [10]:
print(img.shape)

(177, 284, 3)


# Converting to Grayscale

In [ ]:
gray=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

In [ ]:
print(gray)

In [ ]:
print(gray.shape)

In [ ]:
cv2.imshow("Original",img)
cv2.imshow("Grayscale",gray)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Converting RGB Format

In [4]:
RGB=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [5]:
print(RGB)

[[[196 189  98]
  [193 188  96]
  [187 187  97]
  ...
  [ 82 110  23]
  [ 79 101  18]
  [ 75  93  11]]

 [[196 189  98]
  [194 189  98]
  [188 188  98]
  ...
  [ 92 122  34]
  [ 91 113  30]
  [ 89 107  25]]

 [[194 189  98]
  [193 189  98]
  [190 190 100]
  ...
  [ 97 127  39]
  [ 98 120  35]
  [ 96 116  31]]

 ...

 [[ 81 167   8]
  [100 186  27]
  [ 92 179  22]
  ...
  [135  89  29]
  [111  92  36]
  [ 98  92  40]]

 [[ 93 181  21]
  [101 189  29]
  [ 77 164   7]
  ...
  [136  90  28]
  [113  94  36]
  [ 99  94  38]]

 [[ 89 180  17]
  [ 86 176  16]
  [ 78 168  11]
  ...
  [135  92  24]
  [106  88  24]
  [ 98  92  30]]]


In [6]:
print(RGB.shape)

(177, 284, 3)


In [7]:
cv2.imshow("Original",img)
cv2.imshow("RGB",RGB)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Color Channel Splitting

In [15]:
(R,G,B)=cv2.split(RGB)

In [16]:
cv2.namedWindow("Blue",cv2.WINDOW_NORMAL)
cv2.namedWindow("Green",cv2.WINDOW_NORMAL)
cv2.namedWindow("Red",cv2.WINDOW_NORMAL)

In [17]:
cv2.imshow("Blue",B)
cv2.imshow("Green",G)
cv2.imshow("Red",R)

In [18]:
cv2.waitKey(0)
cv2.destroyAllWindows()